apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ss-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.global-static-ip-name: vtn-ss-reserved-1

spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: somethingspecial-service
          servicePort: 3000