kind: Deployment
apiVersion: apps/v1
metadata:
  name: somethingspecial-deployment
spec:
  selector:
    matchLabels:
      app: somethingspecial
  replicas: {{.Values.scale}}
  template:
    metadata:
      labels:
        app: somethingspecial
    spec:
      containers:
      - name: somethingspecial
        image: gcr.io/somethingspecial-256820/somethingspecial@sha256:4cf9ddc8c7b9701f4e0c3c2b13cd800e51de59c49881d59cd3d2e2c132cb60a9
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: somethingspecial-service
  labels:
    app: somethingspecial-service
    service: somethingspecial-service
spec:
  selector:
    app: somethingspecial
  ports:
    - protocol: TCP
      name: http
      port: 3000
      targetPort: 3000
  type: NodePort